# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=26.1.2
#	yarn_mappings=1.21.11+build.3
	loader_version=0.19.2
	modmenu_version=18.0.0-beta.1

# Mod Properties
	mod_version = 1.4.0-26.1.2

	maven_group = fr.alice
	archives_base_name = More-QoL

# Dependencies
	fabric_version=0.149.0+26.1.2
